[tool.poetry]
name = "video-reverse-bot"
description = ""
version = "1.0.0"
authors = ["BlindfoldedSurgery <team@blindfolded.surgery>"]
license = "MIT"
packages = [
    { include = "app", from = "src" }
]

[[tool.poetry.source]]
name = "internal"
url = "https://pypi.bjoernpetersen.net"
priority = "explicit"

[tool.poetry.dependencies]
bs-config = { version = "1.0.2", extras = ["dotenv"], source = "internal" }
certifi = "2024.7.4"
# dictated by python-telegram-bot
httpx = "*"
python = "~3.12"
python-telegram-bot = "21.3"
sentry-sdk = "^2.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "~1.10"
pytest = "^8.0.0"
ruff = "0.5.1"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false

[tool.ruff.lint]
extend-select = [
    "I001",
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
