---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bot-secrets
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: bot-secrets
  dataFrom:
    - find:
        path: "VIDEO_REVERSE_"
      rewrite:
        - regexp:
            source: "VIDEO_REVERSE_(.+)"
            target: "$1"
